# Generated by Django 5.1.3 on 2026-04-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='duration_type',
            field=models.CharField(choices=[('FULL_DAY', 'Full Day'), ('HALF_DAY', 'Half Day')], default='FULL_DAY', max_length=20),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual'), ('SICK', 'Sick'), ('EARNED', 'Earned'), ('LOP', 'Loss Of Pay')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual'), ('SICK', 'Sick'), ('EARNED', 'Earned'), ('LOP', 'Loss Of Pay')], max_length=20),
        ),
    ]
