# Generated by Codex on 2026-04-10

from django.db import migrations


def seed_missing_leave_balances(apps, schema_editor):
    Employee = apps.get_model("employees", "Employee")
    LeaveBalance = apps.get_model("leave_management", "LeaveBalance")

    leave_types = ["CASUAL", "SICK", "EARNED", "LOP"]
    existing_pairs = set(LeaveBalance.objects.values_list("employee_id", "leave_type"))
    balances_to_create = []

    for employee_id in Employee.objects.values_list("id", flat=True):
        for leave_type in leave_types:
            if (employee_id, leave_type) in existing_pairs:
                continue
            balances_to_create.append(
                LeaveBalance(
                    employee_id=employee_id,
                    leave_type=leave_type,
                    allocated_days=0,
                    used_days=0,
                )
            )

    if balances_to_create:
        LeaveBalance.objects.bulk_create(balances_to_create)


class Migration(migrations.Migration):
    dependencies = [
        ("leave_management", "0002_leaverequest_duration_type_and_more"),
        ("employees", "0002_employee_department_role_employee_shift_end_time_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_missing_leave_balances, migrations.RunPython.noop),
    ]
