# Generated by Django 5.1.3 on 2026-04-10 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_organizationsettings_shifttemplate'),
        ('leave_management', '0004_leavebalance_leave_manag_employe_829aba_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('casual_days_onboarding', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('sick_days_onboarding', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('earned_days_onboarding', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('monthly_sick_leave_limit', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('monthly_earned_leave_limit', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('compensate_with_earned_leave', models.BooleanField(default=True)),
                ('excess_leave_becomes_lop', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Leave policies',
            },
        ),
        migrations.CreateModel(
            name='EarnedLeaveAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(db_index=True)),
                ('days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('approver_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earned_leave_adjustment_reviews', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_leave_adjustments', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'work_date', 'status'], name='leave_manag_employe_91df03_idx')],
            },
        ),
    ]
