# Generated by Django 5.1.3 on 2026-04-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_leavepolicy_earnedleaveadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='lop_days_applied',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
