# Generated by Django 5.1.3 on 2026-04-13 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_employee_ctc_per_annum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.CharField(blank=True, max_length=240)),
                ('body', models.TextField()),
                ('audience_type', models.CharField(choices=[('ALL', 'All Employees'), ('ROLE', 'Role'), ('DEPARTMENT', 'Department'), ('INDIVIDUAL', 'Individual')], default='ALL', max_length=20)),
                ('role', models.CharField(blank=True, choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('HR', 'HR'), ('ACCOUNTS', 'Accounts'), ('ADMIN', 'Admin')], max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('show_on_dashboard', models.BooleanField(default=True)),
                ('requires_acknowledgement', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='employees.department')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField()),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='announcements.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_acknowledgements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acknowledged_at'],
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_published', 'starts_at'], name='announcemen_is_publ_f92b28_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['audience_type', 'role'], name='announcemen_audienc_8028ca_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementacknowledgement',
            index=models.Index(fields=['user', 'acknowledged_at'], name='announcemen_user_id_17850b_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementacknowledgement',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='unique_announcement_acknowledgement'),
        ),
    ]
