# Generated by Django 5.1.3 on 2026-04-13 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_employee_ctc_per_annum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('min_rating', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('max_rating', models.DecimalField(decimal_places=1, default=5, max_digits=4)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('self_review_due_date', models.DateField()),
                ('manager_review_due_date', models.DateField()),
                ('hr_review_due_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=20)),
                ('rating_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_cycles', to='performance.ratingscale')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('GOAL', 'Goal'), ('KRA', 'KRA'), ('KPI', 'KPI')], default='GOAL', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.CharField(blank=True, max_length=160)),
                ('progress_value', models.CharField(blank=True, max_length=160)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='performance.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_goals', to='employees.employee')),
            ],
            options={
                'ordering': ['cycle__start_date', 'employee__employee_id', 'title'],
                'indexes': [models.Index(fields=['cycle', 'employee', 'status'], name='performance_cycle_i_ce989d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SELF_PENDING', 'Self Review Pending'), ('MANAGER_PENDING', 'Manager Review Pending'), ('HR_PENDING', 'HR Review Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_index=True, default='SELF_PENDING', max_length=20)),
                ('self_summary', models.TextField(blank=True)),
                ('self_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('manager_summary', models.TextField(blank=True)),
                ('manager_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('hr_summary', models.TextField(blank=True)),
                ('final_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_performance_reviews', to='employees.employee')),
            ],
            options={
                'ordering': ['-cycle__start_date', 'employee__employee_id'],
                'indexes': [models.Index(fields=['status', 'cycle'], name='performance_status_07706e_idx'), models.Index(fields=['employee', 'cycle'], name='performance_employe_1ed0a7_idx')],
                'constraints': [models.UniqueConstraint(fields=('cycle', 'employee'), name='unique_performance_review_cycle_employee')],
            },
        ),
        migrations.AddIndex(
            model_name='performancecycle',
            index=models.Index(fields=['status', 'start_date'], name='performance_status_01fd90_idx'),
        ),
    ]
