# Generated by Django 5.1.3 on 2026-04-10 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_employee_secondary_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('country_code', models.CharField(db_index=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeHolidayAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_assignment', to='employees.employee')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='holidays.holidaycalendar')),
            ],
            options={
                'ordering': ['employee__employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('date', models.DateField(db_index=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='holidays.holidaycalendar')),
            ],
            options={
                'ordering': ['date', 'name'],
                'indexes': [models.Index(fields=['calendar', 'date'], name='holidays_ho_calenda_a3d8c2_idx')],
                'constraints': [models.UniqueConstraint(fields=('calendar', 'date', 'name'), name='unique_holiday_calendar_date_name')],
            },
        ),
    ]
