# Generated by Django 5.1.3 on 2026-04-10 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('assigned_role', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], db_index=True, default='QUEUED', max_length=20)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMMENTED', 'Commented'), ('SYSTEM', 'System')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('approval_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflow.approvalinstance')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('module', models.CharField(choices=[('leave_request', 'Leave Request'), ('attendance_regularization', 'Attendance Regularization')], db_index=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('condition_field', models.CharField(blank=True, max_length=120)),
                ('condition_operator', models.CharField(choices=[('ALWAYS', 'Always'), ('EQUALS', 'Equals'), ('NOT_EQUALS', 'Not Equals'), ('GTE', 'Greater Than Or Equal'), ('LTE', 'Less Than Or Equal'), ('IN', 'In')], default='ALWAYS', max_length=20)),
                ('condition_value', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['module', 'priority', 'name'],
                'indexes': [models.Index(fields=['module', 'is_active', 'priority'], name='workflow_wo_module_fd6f68_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('leave_request', 'Leave Request'), ('attendance_regularization', 'Attendance Regularization')], db_index=True, max_length=64)),
                ('object_id', models.PositiveBigIntegerField()),
                ('current_step_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_assignments', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workflow.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='workflow_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_instances', to='workflow.workflowassignment'),
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('sequence', models.PositiveIntegerField()),
                ('assignment_type', models.CharField(choices=[('ROLE', 'Role'), ('PRIMARY_MANAGER', 'Primary Manager'), ('SECONDARY_MANAGER', 'Secondary Manager'), ('USER', 'Specific User')], max_length=30)),
                ('role', models.CharField(blank=True, choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('HR', 'HR'), ('ADMIN', 'Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('condition_field', models.CharField(blank=True, max_length=120)),
                ('condition_operator', models.CharField(choices=[('ALWAYS', 'Always'), ('EQUALS', 'Equals'), ('NOT_EQUALS', 'Not Equals'), ('GTE', 'Greater Than Or Equal'), ('LTE', 'Less Than Or Equal'), ('IN', 'In')], default='ALWAYS', max_length=20)),
                ('condition_value', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflow')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_instances', to='workflow.workflowstep'),
        ),
        migrations.AddIndex(
            model_name='workflowassignment',
            index=models.Index(fields=['module', 'status'], name='workflow_wo_module_2197d5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowassignment',
            index=models.Index(fields=['content_type', 'object_id'], name='workflow_wo_content_60e4a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'sequence'), name='unique_workflow_step_sequence'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['assigned_user', 'status'], name='workflow_ap_assigne_b25526_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['workflow_assignment', 'status'], name='workflow_ap_workflo_544dbf_idx'),
        ),
    ]
