# Generated by Django 5.1.3 on 2026-04-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='role',
            field=models.CharField(blank=True, choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('HR', 'HR'), ('ACCOUNTS', 'Accounts'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
