# Generated by Django 5.1.3 on 2026-04-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_workflowstep_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='module',
            field=models.CharField(choices=[('leave_request', 'Leave Request'), ('attendance_regularization', 'Attendance Regularization'), ('performance_review', 'Performance Review'), ('lifecycle_case', 'Lifecycle Case'), ('payroll_release', 'Payroll Release')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='workflowassignment',
            name='module',
            field=models.CharField(choices=[('leave_request', 'Leave Request'), ('attendance_regularization', 'Attendance Regularization'), ('performance_review', 'Performance Review'), ('lifecycle_case', 'Lifecycle Case'), ('payroll_release', 'Payroll Release')], db_index=True, max_length=64),
        ),
    ]
