# Generated by Django 5.1.3 on 2026-04-13 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_employee_ctc_per_annum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roster_date', models.DateField(db_index=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('BULK', 'Bulk'), ('ROTATION', 'Rotation')], default='MANUAL', max_length=20)),
                ('is_holiday', models.BooleanField(default=False)),
                ('is_conflicted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='employees.employee')),
                ('shift_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='employees.shifttemplate')),
            ],
            options={
                'ordering': ['roster_date', 'employee__employee_id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conflict_type', models.CharField(choices=[('HOLIDAY', 'Holiday'), ('DUPLICATE', 'Duplicate'), ('OFFBOARDING', 'Offboarding'), ('INACTIVE_EMPLOYEE', 'Inactive Employee')], max_length=30)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_schedule_conflicts', to=settings.AUTH_USER_MODEL)),
                ('roster_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='scheduling.shiftrosterentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRotationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rotation_pattern', models.JSONField(blank=True, default=list, help_text='Ordered list of shift template ids.')),
                ('holiday_strategy', models.CharField(choices=[('SKIP', 'Skip'), ('MARK_CONFLICT', 'Mark Conflict'), ('ASSIGN_ANYWAY', 'Assign Anyway')], default='MARK_CONFLICT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_rotation_rules', to='employees.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='shiftrosterentry',
            index=models.Index(fields=['roster_date', 'is_conflicted'], name='scheduling__roster__b99055_idx'),
        ),
        migrations.AddConstraint(
            model_name='shiftrosterentry',
            constraint=models.UniqueConstraint(fields=('employee', 'roster_date'), name='unique_roster_entry_employee_date'),
        ),
        migrations.AddIndex(
            model_name='scheduleconflict',
            index=models.Index(fields=['conflict_type', 'is_resolved'], name='scheduling__conflic_b9c8e6_idx'),
        ),
    ]
