# Generated by Django 5.1.3 on 2026-04-10 18:17

from django.db import migrations, models


def backfill_open_attendance_sessions(apps, schema_editor):
    Attendance = apps.get_model('attendance', 'Attendance')
    for attendance in Attendance.objects.filter(check_in__isnull=False, check_out__isnull=True):
        attendance.current_session_check_in = attendance.check_in
        attendance.current_session_break_minutes = attendance.break_minutes
        attendance.break_minutes = 0
        attendance.save(
            update_fields=['current_session_check_in', 'current_session_break_minutes', 'break_minutes']
        )


def revert_open_attendance_sessions(apps, schema_editor):
    Attendance = apps.get_model('attendance', 'Attendance')
    for attendance in Attendance.objects.filter(current_session_check_in__isnull=False):
        attendance.break_minutes = (attendance.break_minutes or 0) + (attendance.current_session_break_minutes or 0)
        attendance.save(update_fields=['break_minutes'])


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_break_minutes_attendance_break_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='current_session_break_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='current_session_check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_open_attendance_sessions, revert_open_attendance_sessions),
    ]
