# Generated by Django 5.1.3 on 2026-04-10 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_current_session_break_minutes_and_more'),
        ('employees', '0003_employee_secondary_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRegularization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('requested_check_in', models.DateTimeField()),
                ('requested_check_out', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('approver_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('HALF_DAY', 'Half Day'), ('REMOTE', 'Remote'), ('ABSENT', 'Absent')], db_index=True, default='PRESENT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'attendance_date', 'status'], name='attendance__employe_cd4875_idx'),
        ),
        migrations.AddField(
            model_name='attendanceregularization',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_regularization_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceregularization',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_regularizations', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='attendanceregularization',
            index=models.Index(fields=['employee', 'date', 'status'], name='attendance__employe_7d7734_idx'),
        ),
    ]
