# Generated by Django 5.1.3 on 2026-04-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('metric_key', models.CharField(choices=[('HEADCOUNT', 'Headcount'), ('ATTRITION', 'Attrition'), ('LEAVE_TREND', 'Leave Trend'), ('OVERTIME_TREND', 'Overtime Trend'), ('PAYROLL_READINESS', 'Payroll Readiness'), ('DOCUMENT_EXPIRY', 'Document Expiry')], db_index=True, max_length=40)),
                ('role_scope', models.CharField(blank=True, max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-snapshot_date', 'metric_key'],
                'indexes': [models.Index(fields=['metric_key', 'snapshot_date'], name='analytics_a_metric__d26b4c_idx')],
                'constraints': [models.UniqueConstraint(fields=('snapshot_date', 'metric_key', 'role_scope'), name='unique_analytics_snapshot_scope')],
            },
        ),
    ]
