# Generated by Django 5.1.3 on 2026-04-13 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('module', models.CharField(choices=[('LEAVE', 'Leave'), ('ATTENDANCE', 'Attendance'), ('PAYROLL', 'Payroll'), ('COMPLIANCE', 'Compliance'), ('LIFECYCLE', 'Lifecycle')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('condition_field', models.CharField(blank=True, max_length=120)),
                ('condition_operator', models.CharField(choices=[('ALWAYS', 'Always'), ('EQUALS', 'Equals'), ('NOT_EQUALS', 'Not Equals'), ('GTE', 'Greater Than Or Equal'), ('LTE', 'Less Than Or Equal'), ('IN', 'In'), ('CONTAINS', 'Contains')], default='ALWAYS', max_length=20)),
                ('condition_value', models.JSONField(blank=True, null=True)),
                ('effect_type', models.CharField(choices=[('WARN', 'Warn'), ('BLOCK', 'Block'), ('FLAG', 'Flag')], default='WARN', max_length=20)),
                ('effect_message', models.CharField(blank=True, max_length=240)),
                ('effect_payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['module', 'priority', 'name'],
                'indexes': [models.Index(fields=['module', 'is_active', 'priority'], name='policy_engi_module_4be63d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PolicyEvaluationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('LEAVE', 'Leave'), ('ATTENDANCE', 'Attendance'), ('PAYROLL', 'Payroll'), ('COMPLIANCE', 'Compliance'), ('LIFECYCLE', 'Lifecycle')], db_index=True, max_length=30)),
                ('object_id', models.PositiveBigIntegerField()),
                ('triggered', models.BooleanField(db_index=True, default=False)),
                ('effect_type', models.CharField(blank=True, choices=[('WARN', 'Warn'), ('BLOCK', 'Block'), ('FLAG', 'Flag')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_evaluation_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_logs', to='policy_engine.policyrule')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'triggered', 'created_at'], name='policy_engi_module_138e12_idx'), models.Index(fields=['content_type', 'object_id'], name='policy_engi_content_736cd6_idx')],
            },
        ),
    ]
