# Generated by Django 5.1.3 on 2026-04-10 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_employee_ctc_per_annum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_month', models.DateField(help_text='Normalized to the first day of the payroll month.')),
                ('gross_monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fixed_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lop_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('lop_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_in_month', models.PositiveSmallIntegerField(default=0)),
                ('payable_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payroll_month', 'employee__employee_id'],
                'indexes': [models.Index(fields=['payroll_month'], name='payroll_pay_payroll_b6e21a_idx'), models.Index(fields=['employee', 'payroll_month'], name='payroll_pay_employe_88a670_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'payroll_month'), name='unique_employee_payroll_month')],
            },
        ),
    ]
