# Generated by Django 5.1.3 on 2026-04-13 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_employee_ctc_per_annum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffboardingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice_start_date', models.DateField()),
                ('last_working_day', models.DateField()),
                ('actual_exit_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('exit_interview_notes', models.TextField(blank=True)),
                ('asset_clearance_status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared')], default='PENDING', max_length=20)),
                ('final_settlement_status', models.CharField(choices=[('PENDING', 'Pending'), ('HANDED_OFF', 'Handed Off'), ('SETTLED', 'Settled')], default='PENDING', max_length=20)),
                ('handoff_notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_cases', to='employees.employee')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_offboarding_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OffboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('owner_role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('HR', 'HR'), ('ACCOUNTS', 'Accounts'), ('ADMIN', 'Admin')], default='HR', max_length=20)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_offboarding_tasks', to=settings.AUTH_USER_MODEL)),
                ('offboarding_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lifecycle.offboardingcase')),
            ],
            options={
                'ordering': ['offboarding_case', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('employment_type', models.CharField(blank=True, max_length=20)),
                ('default_duration_days', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_plans', to='employees.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='NOT_STARTED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboardings', to='employees.employee')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_onboardings', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_onboardings', to='lifecycle.onboardingplan')),
            ],
            options={
                'ordering': ['-start_date', 'employee__employee_id'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('owner_role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('HR', 'HR'), ('ACCOUNTS', 'Accounts'), ('ADMIN', 'Admin')], default='HR', max_length=20)),
                ('task_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('POLICY', 'Policy'), ('ACCESS', 'Access'), ('TRAINING', 'Training')], default='DOCUMENT', max_length=20)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('due_offset_days', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='lifecycle.onboardingplan')),
            ],
            options={
                'ordering': ['plan', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('owner_role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('HR', 'HR'), ('ACCOUNTS', 'Accounts'), ('ADMIN', 'Admin')], default='HR', max_length=20)),
                ('task_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('POLICY', 'Policy'), ('ACCESS', 'Access'), ('TRAINING', 'Training')], max_length=20)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_onboarding_tasks', to=settings.AUTH_USER_MODEL)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lifecycle.employeeonboarding')),
                ('template_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instantiated_tasks', to='lifecycle.onboardingtasktemplate')),
            ],
            options={
                'ordering': ['onboarding', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('CONFIRMATION', 'Probation Confirmation'), ('PROMOTION', 'Promotion'), ('ROLE_CHANGE', 'Role Change'), ('COMPENSATION_REVISION', 'Compensation Revision')], db_index=True, max_length=30)),
                ('proposed_designation', models.CharField(blank=True, max_length=150)),
                ('proposed_role', models.CharField(blank=True, choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('HR', 'HR'), ('ACCOUNTS', 'Accounts'), ('ADMIN', 'Admin')], max_length=20)),
                ('proposed_department_role', models.CharField(blank=True, choices=[('MEMBER', 'Member'), ('TEAM_LEAD', 'Team Lead')], max_length=20)),
                ('proposed_ctc_per_annum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proposed_effective_date', models.DateField()),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_employee_change_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='employees.employee')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'change_type', 'status'], name='lifecycle_e_employe_eca153_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='offboardingcase',
            index=models.Index(fields=['employee', 'status'], name='lifecycle_o_employe_88a014_idx'),
        ),
        migrations.AddIndex(
            model_name='offboardingtask',
            index=models.Index(fields=['offboarding_case', 'status'], name='lifecycle_o_offboar_56386a_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeonboarding',
            index=models.Index(fields=['employee', 'status'], name='lifecycle_e_employe_f719b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='onboardingtasktemplate',
            constraint=models.UniqueConstraint(fields=('plan', 'sequence', 'title'), name='unique_onboarding_task_template'),
        ),
        migrations.AddIndex(
            model_name='employeeonboardingtask',
            index=models.Index(fields=['onboarding', 'status'], name='lifecycle_e_onboard_33cb99_idx'),
        ),
    ]
