# Generated by Django 5.1.3 on 2026-04-10 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('TEAM_LEAD', 'Team Lead')], default='MEMBER', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_end_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_name',
            field=models.CharField(default='General', max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
