# Generated by Django 5.1.3 on 2026-04-10 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_department_role_employee_shift_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='secondary_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_team_members', to='employees.employee'),
        ),
    ]
