# Generated by Django 5.1.3 on 2026-04-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LEAVE_APPLIED', 'Leave Applied'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('WORKFLOW_PENDING', 'Workflow Pending'), ('MISSING_ATTENDANCE', 'Missing Attendance'), ('REGULARIZATION', 'Attendance Regularization'), ('DOCUMENT_EXPIRY', 'Document Expiry'), ('DOCUMENT_VERIFIED', 'Document Verified'), ('PERFORMANCE_REVIEW', 'Performance Review'), ('ONBOARDING', 'Onboarding'), ('OFFBOARDING', 'Offboarding'), ('LIFECYCLE', 'Lifecycle'), ('PAYROLL', 'Payroll'), ('ANNOUNCEMENT', 'Announcement'), ('HELPDESK', 'Helpdesk'), ('GENERIC', 'Generic')], default='GENERIC', max_length=40),
        ),
    ]
